export const InspectionLabelMapping: Record<string, string> = {
  INEX_INS_1: '운전석 / 동반석 헤드램프 점등',
  INEX_INS_2: '운전석 / 동반석 브레이크,미등',
  INEX_INS_3: '운전석 / 동반석 안개등',
  INEX_INS_4: '범퍼(앞)',
  INEX_INS_5: '범퍼(뒤)',
  INEX_INS_6: '백미러(좌)',
  INEX_INS_7: '백미러(우)',
  INEX_INS_8: '앞유리',
  INEX_INS_9: '뒷유리',
  INEX_INS_10: '앞유리(좌)',
  INEX_INS_11: '앞유리(우)',
  INEX_INS_12: '뒷유리(좌)',
  INEX_INS_13: '뒷유리(우)',
  INEX_INS_14: '앞휠(좌)',
  INEX_INS_15: '앞휠(우)',
  INEX_INS_16: '뒷휠(좌)',
  INEX_INS_17: '뒷휠(우)',
  INEX_INS_18: '앞타이어(좌)',
  INEX_INS_19: '앞타이어(우)',
  INEX_INS_20: '뒷타이어(좌)',
  INEX_INS_21: '뒷타이어(우)',
  INEX_INS_22: '내장재',
  INEX_INS_23: '앞 시트(외관)',
  EXPA_INS_1: '본네트',
  EXPA_INS_2: '앞펜더:좌',
  EXPA_INS_3: '앞펜더:우',
  EXPA_INS_4: '앞문:좌',
  EXPA_INS_5: '앞문:우',
  EXPA_INS_6: '뒷문:좌',
  EXPA_INS_7: '뒷문:우',
  EXPA_INS_8: '루프',
  EXPA_INS_9: '트렁크',
  FRA_INS_1: '라디에이터 서포트(볼트체결)',
  FRA_INS_2: '프론트패널',
  FRA_INS_3: '크로스멤버(프레임바디)',
  FRA_INS_4: '데쉬패널:앞',
  FRA_INS_5: '사이드멤버앞:좌',
  FRA_INS_6: '인사이드패널:좌',
  FRA_INS_7: '훨하우스앞:좌',
  FRA_INS_8: 'A필러:좌',
  FRA_INS_9: 'B필러:좌',
  FRA_INS_10: '사이드실:좌',
  FRA_INS_13: 'A필러:좌',
  FRA_INS_14: 'A필러:우',
  FRA_INS_15: '사이드실:좌',
  FRA_INS_16: '사이드실:우',
  FRA_INS_17: '쿼터패널:좌',
  FRA_INS_18: '쿼터패널:우',
  FRA_INS_19: '훨하우스뒤:좌',
  FRA_INS_20: '휠하우스뒤:우',
  FRA_INS_21: '사이드멤버뒤:좌',
  FRA_INS_22: '사이드멤버뒤:우',
  FRA_INS_23: '플로어패널d',
  FRA_INS_24: '패키지트레이',
  FRA_INS_25: '트렁크플로어패널',
  FRA_INS_26: '리어패널'
};
